src/Entity/Inter.php
<?php

namespace App\Entity;

use App\Repository\InterRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=InterRepository::class)
 */
class Inter
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $Anomalie;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $Salaire;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="inters")
     */
    private $technicien;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $presence;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getAnomalie(): ?string
    {
        return $this->Anomalie;
    }

    public function setAnomalie(?string $Anomalie): self
    {
        $this->Anomalie = $Anomalie;

        return $this;
    }

    public function getSalaire(): ?float
    {
        return $this->Salaire;
    }

    public function setSalaire(?float $Salaire): self
    {
        $this->Salaire = $Salaire;

        return $this;
    }

    public function getTechnicien(): ?User
    {
        return $this->technicien;
    }

    public function setTechnicien(?User $technicien): self
    {
        $this->technicien = $technicien;

        return $this;
    }

    public function isPresence(): ?bool
    {
        return $this->presence;
    }

    public function setPresence(?bool $presence): self
    {
        $this->presence = $presence;

        return $this;
    }
}

src/Form/InterType.php
<?php

namespace App\Form;

use App\Entity\User;
use App\Entity\Inter;
use App\Repository\UserRepository;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;

class InterType extends AbstractType
{
    private $userRepository; 

    public function __construct(UserRepository $userRepository)
    {
        $this->userRepository = $userRepository;
    }
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('Date', DateType::class, [
                'required' => true, 
                'widget' => "single_text",
            ])
            ->add('Anomalie')
            ->add('Salaire', IntegerType::class, [
            ])
            ->add('technicien', EntityType::class, [
                'class' => User::class,
                'choices' => $this->userRepository->findByPoste('tech'),
                'choice_label' => function(User $user){
                    return $user->getNom() .' '. $user->getPrenom();
                }
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Inter::class,
        ]);
    }
}

src/Controller/InterController.php
<?php

namespace App\Controller;

use DateTime;
use App\Entity\Inter;
use App\Form\InterType;
use App\Form\InterFormType;
use App\Repository\UserRepository;
use App\Repository\InterRepository;
use App\Repository\ParametresRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\RequestStack;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

/**
 * @Route("/admin/inter")
 */
class InterController extends AbstractController
{
    private $requestStack;
    /**
     * Constructor
     */
    public function __construct(RequestStack $requestStack)
    {
        $this->requestStack = $requestStack;
    }

    /**
     * @Route("/new", name="app_inter_new")
     */
    public function new_inter(Request $request, EntityManagerInterface $em): Response
    {
        $inter = new Inter;
        $form = $this->createForm(InterFormType::class, $inter);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em->persist($inter);
            $em->flush();
        }

        return $this->render('inter/index.html.twig', [
            'form' => $form->createView()
        ]);
    }
    /**
     * @Route("/", name="inter_jour")
     */
    public function inter_jour(InterRepository $interRepository, EntityManagerInterface $em, Request $request): Response
    {
        $session = $this->requestStack->getSession();
        $date = (new \DateTime('now'))->format('Y-m-d');
        $date_post = $request->query->get('date');

        if ($date_post != null) {
            $date = $date_post;
        }
        $inter_jour = $interRepository->findByDate((new \DateTime($date))->format('Y-m-d'));
        // session pour retour
        $session->set('referer', $request->getUri());

        return $this->render('inter/inter_jour.html.twig', [
            "inter_jour" => $inter_jour,
            "date_url" => $date
        ]);
    }

    /**
     * @Route("/edit/{id}", name="edit_inter")
     */
    public function modifier_inter($id, Request $request, EntityManagerInterface $em, InterRepository $interRepository): Response
    {
        // Recuperation sessions
        $session = $this->requestStack->getSession();

        $source_url = ($request->query->get('source') ? $request->query->get('source') : 'app_menu');
        $source_param = $request->query->get('param');
        $backup = $request->query->get('backup');

        $inter = $interRepository->findOneById($id);
        $form = $this->createForm(InterFormType::class, $inter);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em->persist($inter);
            $em->flush();

            //redirection
            $referer = $session->get('referer');
            if ($referer == null) {
                return $this->redirectToRoute('app_home');
            }
            return $this->redirect($referer);
        }

        return $this->render('inter/edit.html.twig', [
            'form' => $form->createView(),
            'id_inter' => $id,
            'source' => $source_url,
            'source_param' => $source_param,
            'backup' => $backup,
            'bouton' => 'Modifier'
        ]);
    }


    /**
     * @Route("/presence/{id}", name="presence")
     */
    public function presence($id, InterRepository $interRepository, Request $request, EntityManagerInterface $em): Response
    {
        $inter = $interRepository->findOneById($id);
        if ($inter->isPresence() == true) {
            $inter->setPresence(False);
        } else {
            $inter->setPresence(True);
        }

        $em->persist($inter);
        $em->flush();


        return $this->json([
            'code' => 200,
            'message'  => 'etat presence ok',
            200
        ]);
    }
    /**
     * @Route("/insertion_mois", name="insertion_inter_mois",  methods={"GET"})
     */
    public function insertion_inter_mois(UserRepository $userRepository, InterRepository $interRepository, EntityManagerInterface $em, ParametresRepository $parametresRepository): Response
    {
        // recuperer toutes les dates entre startDate et $endDate
        function getDatesFromRange($startDate, $endDate)
        {
            $return = array($startDate);
            $start = $startDate;
            $i = 1;
            if (strtotime($startDate) < strtotime($endDate)) {
                while (strtotime($start) < strtotime($endDate)) {
                    $start = date('Y-m-d', strtotime($startDate . '+' . $i . ' days'));
                    $return[] = $start;
                    $i++;
                }
            }

            return $return;
        }

        // recuperer les dates dans les paramètres de la bdd
        $startdate = $parametresRepository->findOneByCle('startdate')->getValeur();
        $enddate = $parametresRepository->findOneByCle('enddate')->getValeur();

        $liste = getDatesFromRange($startdate, $enddate);


        $techs = $userRepository->findByPoste('tech');
        // dd($techs);

        foreach ($liste as $key => $value) {

            $date = (new \DateTime($value));
            // dd($date->format('l'));


            foreach ($techs as $key => $tech) {

                $inter_encours = $interRepository->findByTechAndDate($tech, $date);
                // dd($inter_encours);
                if (!$inter_encours && ($date->format('l')) != 'Sunday') {
                    $inter = new Inter;

                    $inter->setDate($date);
                    $inter->setTechnicien($tech);
                    if (!$inter_encours && ($date->format('l')) != 'Saturday'){
                        $inter->setPresence(true);
                    }
                    $inter->setSalaire($tech->getBasesalaire());

                    $em->persist($inter);
                    $em->flush();
                }
            }
        }

        return $this->redirectToRoute('app_menu');
    }

    /**
     * @Route("/suppression_mois", name="suppression_inter_mois",  methods={"GET"})
     */
    public function suppression_inter_mois(UserRepository $userRepository, InterRepository $interRepository, EntityManagerInterface $em, ParametresRepository $parametresRepository): Response
    {

        // recuperer les dates dans les paramètres de la bdd
        $startdate = $parametresRepository->findOneByCle('startdate')->getValeur();
        $enddate = $parametresRepository->findOneByCle('enddate')->getValeur();

        $liste = $interRepository->findInterBetweenDate($startdate, $enddate);
        // dd($liste);

        foreach ($liste as $key => $value) {
            $em->remove($value);
            $em->flush();
        }

        return $this->redirectToRoute('app_menu');
    }

    /**
     * @Route("/suppression_inter/{id}", name="suppression_inter",  methods={"GET"})
     */
    public function suppression_inter($id, UserRepository $userRepository, InterRepository $interRepository, EntityManagerInterface $em, ParametresRepository $parametresRepository): Response
    {
        $session = $this->requestStack->getSession();

        $inter = $interRepository->findOneById($id);
        $em->remove($inter);
        $em->flush();

        //redirection
        $referer = $session->get('referer');
        if ($referer == null) {
            return $this->redirectToRoute('app_home');
        }
        return $this->redirect($referer);
    }

    /**
     * @Route("/inter_periode/tech/{id}", name="inter_periode_tech")
     */
    public function inter_periode_tech(
        $id,
        UserRepository $userRepository,
        InterRepository $interRepository,
        ParametresRepository $parametresRepository,
        Request $request
    ): Response {

        $session = $this->requestStack->getSession();
        $tech = $userRepository->findOneById($id);
        $mois = ['Janvier', 'Fevrier', 'Mars', 'Avril', 'Mai', 'Juin', 'Juillet', 'Août', 'Septembre', 'Octobre', 'Novembre', 'Décembre'];
       
        $date_debut = new DateTime(($parametresRepository->findOneByCle('startdate'))->getValeur());
        $date_fin = new DateTime(($parametresRepository->findOneByCle('enddate'))->getValeur());
        $periode = (new \DateTime('now'))->format('m');

        $periode_param = $request->query->get('mois');
        
        if (isset($periode_param) && $periode_param != null){
            $periode = $periode_param;
        }

        $annee = (new DateTime("now"))->format('Y');

        if (isset($periode)) {
            $periode_date_debut = new DateTime($annee . '-' . $periode);
            $periode_date_fin = new DateTime($annee . '-' . $periode);
            $date_debut  = $periode_date_debut->modify('first day of this month');
            $date_fin  = $periode_date_fin->modify('last day of this month');
        }

        $inter_list = $interRepository->findInterByTechPeriod($id, $date_debut, $date_fin);
        // session pour retour
        $session->set('referer', $request->getUri());

        return $this->render('inter/inter_tech.html.twig', [
            "inter_list" => $inter_list,
            "date_debut" => $date_debut->format('d-m-Y'),
            "date_fin" => $date_fin->format('d-m-Y'),
            "tech" => $tech,
            "mois_list" => $mois,
            "periode" => $periode
        ]);
    }
}

templates/inter/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modifier{% endblock %}

{% block body %}
<div class="row d-flex justify-content-center">
    <div class="col-md-3">
        <h1>Modifier Inter</h1>

        <div class="m-2">
            {{ form_start(form) }}
            {{ form_row(form.Date) }}
            {{ form_row(form.Anomalie) }}
            {{ form_row(form.Salaire) }}
            {{ form_row(form.technicien) }}    
            <button type="submit" class="btn btn-primary w-100">Modifier</button>
            {{ form_end(form) }}
            <a href="{{path('suppression_inter', {id:id_inter})}}"  type="button" onclick="return confirm('Etes-vous sur de vouloir supprimer cette inter')" class="btn btn-warning w-100 mt-1"  title="Retour">Supprimer</a>
            <a type="button" onclick="history.go(-1)" class="btn btn-secondary w-100 mt-1"  title="Retour">Retour</a>
        </div>

    </div>
</div>
<div class="mb-footer"></div>

{% endblock %}

templates/inter/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ bouton is defined  ? bouton : 'Créer'}}{% endblock %}

{% block body %}
<div class="row d-flex justify-content-center">
    <div class="col-md-3">
        <h1>Nouvelle inter</h1>

        <div class="m-2">
            {{ form_start(form) }}
            {{ form_row(form.technicien) }}    
            {{ form_row(form.Date, {
                attr : {
                    value : "now"|date("Y-m-d") 
                }
            }) }}
            {{ form_row(form.Anomalie) }}
            {{ form_row(form.Salaire, {
                attr : {
                    value : 80
                }
            }) }}
            <button type="submit" class="btn btn-primary w-100">{{ bouton is defined ? bouton : 'Créer'}}</button>
            {{ form_end(form) }}
            <a type="button" onclick="history.go(-1)" class="btn btn-secondary w-100 mt-1"  title="Retour">Retour</a>
        </div>

    </div>
</div>
<div class="mb-footer"></div>

{% endblock %}

templates/inter/inter_jour.html.twig
{% extends 'base.html.twig' %}

{% block title %}Inter du jour{% endblock %}

{% block body %}
<div class="row d-flex justify-content-center">
  <div class="col-md-3">


    <div class="text-center mt-1">

      <h1 class="">Inters du jour</h1>
      <span class="badge bg-info bg-sm">{{date_url|date('d/m/Y')}}</span>
    </div>

    <div class="text-center mb-2">
      <input type="date" id="date" name="date" value="{{date_url}}" onchange="submitdate()">
    </div>

    {% for inter in inter_jour %}
    {% if inter.presence == 1 %}

    <div class="alert alert-success d-flex justify-content-between">
      <a href="{{ path ('edit_inter', {id: inter.id})}}?source=inter_jour&param="
        class="text-decoration-none text-dark">
        <span>{{ inter.technicien.nom}} {{ inter.technicien.prenom}} </span>
        {% if inter.anomalie is not null %}
        <i class="fas fa-exclamation-triangle text-danger"></i>
        {% endif %}
      </a>
      <a href="{{ path ('presence', {id : inter.id} )}}" class="presence" onclick="onClickBtn(this)">
        <input type="checkbox" checked data-toggle="toggle" data-onstyle="success" data-offstyle="warning"
          data-on="Present" data-off="Absent">
      </a>
    </div>

    {% else %}
    <div class="alert alert-secondary d-flex justify-content-between">
      <a href="{{ path ('edit_inter', {id: inter.id})}}?source=inter_jour&param="
        class="text-decoration-none text-dark">
        <span>{{ inter.technicien.nom}} {{ inter.technicien.prenom}} </span>
      </a>
      <a href="{{ path ('presence', {id : inter.id} )}}" class="presence" onclick="onClickBtn(this)">
        <input type="checkbox" data-toggle="toggle" data-onstyle="success" data-on="Present" data-offstyle="warning"
          data-off="Absent">
      </a>
    </div>
    {% endif %}
    {% endfor %}

  </div>
</div>
{% endblock %}

{% block javascripts %}
<script>
  const domain = window.location.origin;
  let url = domain + "/admin/inter?";

  function submitdate() {
    let date = document.getElementById('date').value;

    window.location.href = url + ('&date=' + date);
  }

  function onClickBtn(obj) {

    if ((obj.closest('div')).classList.contains("alert-success")) {
      (obj.closest('div')).classList.replace("alert-success", "alert-secondary");
    } else {

      (obj.closest('div')).classList.add("alert-secondary");
      (obj.closest('div')).classList.replace("alert-secondary", "alert-success");

    }
    const url = obj.href;
    fetch(url, {
      headers: {
        "X-Requested-With": "XMLHttpRequest"
      }
    })
      .then(response => response.json())
      .catch(e => {
        console.log(e);
      });

  }

</script>


{% endblock %}

templates/inter/inter_tech.html.twig
{% extends 'base.html.twig' %}

{% block title %}Inter Periode{% endblock %}

{% block body %}
    <!--Convertion date-->
    {% set trans_day_hash = {
      "Monday": "Lundi",
      "Tuesday": "Mardi",
      "Wednesday": "Mercredi",
      "Thursday": "Jeudi",
      "Friday": "Vendredi",
      "Saturday": "Samedi",
      "Sunday": "Dimanche"
      }
      %}
<div class="row d-flex justify-content-center">
  <div class="col-md-3">


    <div class="text-center mt-1">

      <h1>Inters Periode</h1>
      <h5><a href="{{path('app_compte')}}"class="text-decoration-none text-dark">{{tech.nom}} {{tech.prenom}}</a></h5>
      <hr>
      <div class="text-center mb-2">
        <select class="form-select" id="mois" aria-label="Mois" onchange="submitPeriod()">
          {% for mois in mois_list %}
          <option {{ loop.index == periode ? 'selected' : '' }} value="{{loop.index}}">{{mois}}</option>            
          {% endfor %}
        </select>
      </div>
      <h5>Entre : <span class="text-primary">{{date_debut}}</span> et  <span class="text-primary">{{date_fin}}</span></h5>

    </div>

    {% for inter in inter_list %}
    {% if inter.presence == 1 %}

    <div class="alert alert-success d-flex justify-content-between">
      <a href="{{ path ('edit_inter', {id: inter.id})}}?source=inter_jour&param="
        class="text-decoration-none text-dark">
        <span>{{trans_day_hash[inter.date|date('l')] }} {{ inter.date|date('d-m-Y')}} </span>
        {% if inter.anomalie is not null %}
        <i class="fas fa-exclamation-triangle text-danger"></i>
        {% endif %}
      </a>
      <a href="{{ path ('presence', {id : inter.id} )}}" class="presence" onclick="onClickBtn(this)">
        <input type="checkbox" checked data-toggle="toggle" data-onstyle="success" data-offstyle="warning"
          data-on="Present" data-off="Absent">
      </a>
    </div>

    {% else %}
    <div class="alert alert-secondary d-flex justify-content-between">
      <a href="{{ path ('edit_inter', {id: inter.id})}}?source=inter_jour&param="
        class="text-decoration-none text-dark">
        <span>{{trans_day_hash[inter.date|date('l')] }} {{ inter.date|date('d-m-Y')}} </span>
      </a>
      <a href="{{ path ('presence', {id : inter.id} )}}" class="presence" onclick="onClickBtn(this)">
        <input type="checkbox" data-toggle="toggle" data-onstyle="success" data-on="Present" data-offstyle="warning"
          data-off="Absent">
      </a>
    </div>
    {% endif %}




    {% endfor %}
    <a type="button" onclick="history.go(-1)" class="btn btn-secondary w-100 mt-1"  title="Retour">Retour</a>

  </div>
</div>
<div class="mb-footer"></div>
<div id="path" data-path="{{path('inter_periode_tech', {id:tech.id})}}"></div>
{% endblock %}

{% block javascripts %}
<script src="{{asset ('assets/js/other.js')}}"></script>

{% endblock %}